### ISSUE TITLE
STM32F401 / F411: it doesn't have a CCRAM, but CCRAM is set to 64K

### ISSUE THREAD

**Issue by t123yh** [ObKo/stm32-cmake#134] opened 2020-06-30 06:59 UTC
From the reference manual these models doesn't have a built-in CCRAM, but it's set to 64K. Probably this should be fixed?

**Comment by Hish15** [comment] 2020-06-30 08:07
You are speaking of CCMRAM I suppose?
https://github.com/ObKo/stm32-cmake/blob/5638bf9141d9d670fa7d9a2a04f07fa26b74dc7a/cmake/gcc_stm32f4.cmake#L70
This is actually CortexM4 related. 
Why do you think that STM32F401 / F411 does not have it ?

**Comment by t123yh** [comment] 2020-06-30 08:13
Because you don't find them in datasheet.

In STM32F405 datasheet you can see the CCM data RAM is at 0x10000000,
![STM32F405](https://user-images.githubusercontent.com/8972552/86101108-5c313b80-baec-11ea-9842-cd95d209d095.png)

But in STM32F401/F411 it's neither found in memory map nor mentioned in the datasheet at all.
![STM32F411](https://user-images.githubusercontent.com/8972552/86101293-a6b2b800-baec-11ea-9d59-8ce60721b3cb.png)

**Comment by Hish15** [comment] 2020-07-03 13:35
👍 This is confirmed [here](https://community.st.com/s/question/0D53W00000BqROfSAN/do-stm32f401-and-f411-have-a-ccram-)

**Comment by ObKo** [comment] 2020-11-01 05:00
Closing due to https://github.com/ObKo/stm32-cmake/pull/117 being merged and made this issue outdated.

**Closed by ObKo** 2020-11-01 05:00 UTC
